### ISSUE TITLE
Appointments: Arrange a new doctor's appointment

### ISSUE THREAD

**Issue by kristina-voit** [kristina-voit/capstone-project#10]
## Value Statement

As a user, I want to click on "neuen Termin finden" and be forwarded to a new window, reaching www.jameda.de, so that I can find a doctor and make an appointment. 

## Description

![Bildschirmfoto 2022-01-05 um 17 12 45](https://user-images.githubusercontent.com/93935781/148250527-9e3c1fbd-7e24-4b09-b96d-fc22f4da55b8.png)

## Complexitiy

S

## Acceptance Criteria

- The user can click on "neuen Termin finden"
- A new window will open, directing to www.jameda.de 

## Tasks

- [x] Create feature branch "card-find-appointment"
- [x] Create "card-find-appointment" - component
- [x] Import component in app.jsx
- [x] Add button "neuen Termin finden"
- [x] Create forwarding to new window, opening www.jameda.de
- [x] Add the corresponding routes
- [x] Add styling
