### ISSUE TITLE
General: Implementation of a navigation menu

### ISSUE THREAD

**Issue by kristina-voit** [kristina-voit/capstone-project#2]
## Value Statement

As a user, I want to click on the navigation menu so that I can access the different sites: Home, Stimmung&Symptome, Medikamente, Arzttermine

## Description

![Bildschirmfoto 2022-01-05 um 13 45 44](https://user-images.githubusercontent.com/93935781/148219805-88600675-ea5d-4b30-9425-113dea6927a1.png)

## Complexitiy

S/M

## Acceptance Criteria

- The user can access the different sites of the app by clicking on the icons
- The selected icon should be in a different style than the unselected icons

## Tasks

- [ ] Create feature branch "navbar"
- [ ]  Create navbar component
- [ ]  Import component in app.jsx
- [x] Build a navigation menu with the following menu points: Home, Stimmung&Symptome, Medikamente, Arzttermine
- [x] Add icons
- [x] Add the corresponding routes
- [ ] Add styling
