### ISSUE TITLE
Mood&Symptoms: Show user's mood in a graph

### ISSUE THREAD

**Issue by kristina-voit** [kristina-voit/capstone-project#20]
## Value Statement

As a user, I want to see my mood in a graph and my daily mood&symptons in a journal card so I can track my mood&symptoms. Also, I want to use a filter method to search for keywords.

## Complexitiy

L

## Acceptance Criteria

- The user can see a graph based on the input of the mood-emojis 
- The user can see a daily card with date, mood, symptoms 
- The user can search for keywords through a search function

## Tasks

- [x] Create feature branch "Symptoms"
- [x] Create components
- [x ] Fetch data from data.js
- [ ] Automatically replace 0,33,66,99 with the corresponding Emoji
- [x] Create search function
- [x] Add styling
