### ISSUE TITLE
Mood&Symptoms: See, add and filter user's daily symptoms&mood

### ISSUE THREAD

**Issue by kristina-voit** [kristina-voit/capstone-project#22]
## Value Statement

As a user, I want to see, add and filter the current entries of my mood&symptoms.

## Description

-

## Complexitiy

L

## Acceptance Criteria

- The user sees the current journal entries
- The user can filter the entries by keyword
- The user can add a new entry
- The user can remove an entry

## Tasks

- [x] Create feature branch 
- [x] Create components
- [x ] Add a "create new entry" function
- [x ] Add a filter function
- [x ] Add function to be saved in local storage
- [ ] Add function to be deleted from local storage
- [x] Import components in app.jsx
- [x] Add the corresponding routes
- [x] Add styling
