### ISSUE TITLE
General: Implementation of the user's greeting

### ISSUE THREAD

**Issue by kristina-voit** [kristina-voit/capstone-project#3]
## Value Statement

As a user, I want to see the current date and a hard-coded greeting on top of my app so that I know the current date

## Description

![Bildschirmfoto 2022-01-05 um 15 36 47](https://user-images.githubusercontent.com/93935781/148235346-09503ba9-10cb-447a-85e0-440fb85774b4.png)

## Complexitiy

S

## Acceptance Criteria

- The user sees the current date with a greeting on top of the app

## Tasks

- [x] Create feature branch "greeting"
- [x] Create header component
- [x] Import component in app.jsx
- [x] Add styling
