### ISSUE TITLE
Medication: Add user's new medicine

### ISSUE THREAD

**Issue by kristina-voit** [kristina-voit/capstone-project#5]
## Value Statement

As a user, I want to add a new medicine including name, producer, dose and dose schedule so that I have an overview on my home screen and don't forget to take my medicine.

## Description

![Bildschirmfoto 2022-01-05 um 16 25 32](https://user-images.githubusercontent.com/93935781/148243089-f93ed617-c211-43a0-9d1b-835324b3f2d6.png)

## Complexitiy

L

## Acceptance Criteria

- The user can click on "Neues Medikament hinzufügen"
- A modal will open to add a new medicine including name, producer, dose and dose schedule
- The user can submit the entry
- The user can reset the entry
- The user can close the modal with "x"

## Tasks

- [x] Create feature branch "card-new-medicine"
- [x] Create "card-new-medicine" - component
- [x] Import component in app.jsx
- [x] Build component with to-do-list
- [x] Add input fields for name, producer, dose and dose schedule
- [x] Add buttons with submit and reset function
- [ ] Add "x" to close the modal
- [x] Add the corresponding routes
- [x] Add styling
