### ISSUE TITLE
Appointments: Show and delete user's doctor's appointments

### ISSUE THREAD

**Issue by kristina-voit** [kristina-voit/capstone-project#8]
## Value Statement

As a user, I want to see my current doctor's appointments so that I have an overview and get in direct contact via telephone or email. 

## Description

![Bildschirmfoto 2022-01-05 um 16 43 19](https://user-images.githubusercontent.com/93935781/148246057-3aa2a928-80dd-40e7-a213-23ed8fb83ccd.png)

## Complexitiy

L

## Acceptance Criteria

- The user is shown the upcoming appointments
- The user can delete the entries
- The user can get in touch with the doctor via telephone or email through the existing buttons
- The user will be forwarded to the preconfigured phone function via click on "Anruf" 
- The user's email client will be opened via click on "Email" with a preconfigured subject line

## Tasks

- [x] Create output cards and show all upcoming appointments with all data from data.js
- [x] Import component
- [ ] Add "x" to delete the entry
- [x] Add button "Anruf"
- [x] Add button "Email" 
- [x] Add button "Website" 
- [ ]  Add onclick-function for buttons
- [x] Add styling
